using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit {}
}
namespace Metek.LspCli.Generators{

[Generator]
public sealed class DriverRequestsGenerator : IIncrementalGenerator
{
    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var configProvider = context.AdditionalTextsProvider
            .Where(at => Path.GetFileName(at.Path) == "DriverRequestsConfig.json")
            .Select((text, ct) => text.GetText(ct)!.ToString());

        var source = configProvider.Collect().Combine(context.CompilationProvider);
        context.RegisterSourceOutput(source, Generate);
    }

    private sealed record Config(
        List<string>? DOC,
        List<string>? TDP,
        List<string>? WSP,
        Dictionary<string, MiscEntry>? Misc
    );

    private sealed record MiscEntry(
        string Table,
        List<string>? Params,
        Dictionary<string, List<string>>? Overloads
    );

    private sealed record MethodResult(
        string ReturnType,
        string ElementType,
        string ParamsTypeName,
        INamedTypeSymbol? ParamsTypeSymbol,
        bool IsCollection,
        bool IsNullable
    );

    private void Generate(SourceProductionContext ctx, (ImmutableArray<string> Configs, Compilation Compilation) source)
    {
        if (source.Configs.Length == 0) return;
        Config? config;
        try { config = JsonSerializer.Deserialize<Config>(source.Configs[0], JsonOpts); }
        catch (Exception ex)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(
                new("MG001", "Config Error", ex.Message, "Gen", DiagnosticSeverity.Error, true), Location.None));
            return;
        }
        if (config is null) return;

        var comp = source.Compilation;
        var sb = new StringBuilder();
        sb.AppendLine("""
            // <auto-generated/>
            using System;
            using System.IO;
            using System.Linq;
            using System.Collections.Generic;
            using System.Threading;
            using System.Threading.Tasks;
            using OmniSharp.Extensions.LanguageServer.Protocol;
            using OmniSharp.Extensions.LanguageServer.Protocol.Models;
            using OmniSharp.Extensions.LanguageServer.Protocol.Document;
            using OmniSharp.Extensions.LanguageServer.Protocol.Workspace;

            namespace Metek.LspCli;

            """);

        var fields = new List<(string name, string type, string? none)>();

        GenerateTable(sb, ctx, comp, "DOCTable", config.DOC, "DOC", fields);
        GenerateTable(sb, ctx, comp, "TDXTable", config.TDP, "TDP", fields);
        GenerateTable(sb, ctx, comp, "WSPTable", config.WSP, "WSP", fields);

        if (config.Misc is not null)
        {
            var groups = config.Misc.GroupBy(m => m.Value.Table switch
            {
                "DOC" => "DOCTable",
                "TDX" or "TDP" => "TDXTable",
                "WSP" => "WSPTable",
                _ => throw new($"Unknown table: {m.Value.Table}"),
            });

            foreach (var group in groups)
            {
                sb.AppendLine($"public partial class {group.Key}\n{{");
                foreach (var (name, entry) in group)
                {
                    var mr = ResolveMethod(comp, name, ctx);
                    if (mr is null) continue;

                    string? resultField = DeriveFieldName(name, mr.IsCollection);
                    GenerateBody(sb, name, entry.Table, mr, resultField, entry.Params);
                    if (resultField is not null) TrackField(fields, mr, resultField);
                    sb.AppendLine();

                    if (entry.Overloads is null) continue;
                    foreach (var (overloadName, overloadParams) in entry.Overloads)
                    {
                        if (overloadParams.Any(p => !entry.Params!.Contains(p)))
                            GenerateBody(sb, name, entry.Table, mr, resultField, overloadParams);
                        else
                            GenerateOverload(sb, name, overloadName, overloadParams, entry.Params!, mr);
                        sb.AppendLine();
                    }
                }
                sb.AppendLine("}\n");
            }
        }

        GenerateDriverResults(sb, fields);
        ctx.AddSource("DriverRequests.g.cs", sb.ToString());
    }

    private void GenerateTable(
        StringBuilder sb, SourceProductionContext ctx, Compilation comp,
        string tableName, List<string>? names, string table,
        List<(string name, string type, string? none)> fields)
    {
        if (names is null || names.Count == 0) return;

        sb.AppendLine($"public partial class {tableName}\n{{");

        foreach (var name in names)
        {
            var mr = ResolveMethod(comp, name, ctx);
            if (mr is null) continue;

            bool shouldCache = name is not "LinkedEditingRange" and not "SignatureHelp";
            string? resultField = shouldCache ? DeriveFieldName(name, mr.IsCollection) : null;

            GenerateBody(sb, name, table, mr, resultField, DefaultParams(table));
            if (shouldCache) TrackField(fields, mr, resultField!);
            sb.AppendLine();
        }

        sb.AppendLine("}\n");
    }

    private void GenerateBody(
        StringBuilder sb, string name, string table, MethodResult mr,
        string? resultField, List<string>? paramNames = null)
    {
        var ps = paramNames ?? DefaultParams(table);
        string paramDecl = string.Join(", ", ps.Select(ParamToDecl));
        string requestName = "Request" + name;

        sb.AppendLine($$"""
                public async Task<{{mr.ReturnType}}> {{name}}({{paramDecl}})
                {
                    var req = await client.{{requestName}}(new {{mr.ParamsTypeName}}
                    {
            """);

        foreach (var (prop, value) in GetKnownSettings(mr.ParamsTypeSymbol, ps))
            sb.AppendLine($"            {prop} = {value},");

        sb.AppendLine("        });");

        if (resultField is not null && mr.IsCollection)
        {
            string key = GetResultsKey(ps);
            sb.AppendLine($$"""
                        if (req is null) return driver.Results.None{{resultField}};
                        driver.Results.{{resultField}}[{{key}}] = req.ToArray();
                        return driver.Results.{{resultField}}[{{key}}];
                """);
        }
        else if (resultField is not null && !mr.IsCollection)
        {
            string key = GetResultsKey(ps);
            if (mr.IsNullable)
                sb.AppendLine($"        if (req is null) return null;");
            sb.AppendLine($$"""
                        driver.Results.{{resultField}}[{{key}}] = req;
                        return req;
                """);
        }
        else
        {
            sb.AppendLine("        return req;");
        }

        sb.AppendLine("    }");
    }

    private static List<(string prop, string value)> GetKnownSettings(INamedTypeSymbol? paramsType, List<string> paramNames)
    {
        var members = new HashSet<string>();
        var curr = paramsType;
        while (curr != null)
        {
            foreach (var m in curr.GetMembers()) members.Add(m.Name);
            curr = curr.BaseType;
        }
        var result = new List<(string, string)>();

        void TryAdd(string prop, string value, params string[] reqs)
        {
            if (members.Contains(prop) && reqs.All(paramNames.Contains)) result.Add((prop, value));
        }

        TryAdd(members.Contains("text_document") ? "text_document" : "TextDocument", 
               "DocumentUri.FromFileSystemPath(Path.GetFullPath(fileName, driver.RootPath))", "fileName");
        TryAdd("Position", "(line, character)", "line", "character");
        TryAdd(members.Contains("range") ? "range" : "Range", 
               "new(startLine, startCharacter, endLine, endCharacter)", "startLine");
        TryAdd("Query", "query", "query");

        var handled = new HashSet<string> { "fileName", "line", "character", "startLine", "startCharacter", "endLine", "endCharacter", "query", "range" };
        result.AddRange(paramNames.Where(p => !handled.Contains(p) && members.Contains(p)).Select(p => (p, p)));

        return result;
    }

    private void GenerateOverload(
        StringBuilder sb, string methodName, string overloadName,
        List<string> overloadParams, List<string> primaryParams, MethodResult mr)
    {
        string paramDecl = string.Join(", ", overloadParams.Select(p => p switch {
            "start" or "end" => $"(int line, int character) {p}",
            "range" => "OmniSharp.Extensions.LanguageServer.Protocol.Models.Range range",
            _ => ParamToDecl(p)
        }));

        sb.AppendLine($"    public async Task<{mr.ReturnType}> {methodName}({paramDecl})\n    {{");

        if (overloadName == "FileOnly")
        {
            sb.AppendLine($"""
                        var fullPath = Path.GetFullPath(fileName, driver.RootPath);
                        var lines = await File.ReadAllLinesAsync(fullPath);
                        int endLine = lines.Length > 0 ? lines.Length - 1 : 0;
                        int endCharacter = lines.Length > 0 ? lines[lines.Length - 1].Length : 0;
                        return await {methodName}(fileName, 0, 0, endLine, endCharacter);
                """);
        }
        else
        {
            var args = primaryParams.Select(pp => {
                if (overloadParams.Contains(pp)) return pp;
                if (overloadParams.Contains("start") && pp is "startLine" or "startCharacter") return "start." + (pp == "startLine" ? "line" : "character");
                if (overloadParams.Contains("end") && pp is "endLine" or "endCharacter") return "end." + (pp == "endLine" ? "line" : "character");
                if (overloadParams.Contains("range")) return pp switch {
                    "startLine" => "range.Start.Line", "startCharacter" => "range.Start.Character",
                    "endLine" => "range.End.Line", "endCharacter" => "range.End.Character", _ => "default"
                };
                return pp is "startCharacter" or "endCharacter" or "startLine" ? "0" : "default";
            });
            sb.AppendLine($"        return await {methodName}({string.Join(", ", args)});");
        }
        sb.AppendLine("    }");
    }

    private MethodResult? ResolveMethod(Compilation comp, string methodName, SourceProductionContext ctx)
    {
        var paramsType = FindParamsType(comp, methodName);
        if (paramsType is null)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(new("MG002", "Type Not Found", $"Params type not found for method '{methodName}'", "Gen", DiagnosticSeverity.Warning, true), Location.None));
            return null;
        }

        var iRequestOfT = comp.GetTypeByMetadataName("MediatR.IRequest`1");
        var responseType = paramsType.AllInterfaces
            .FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, iRequestOfT))
            ?.TypeArguments[0] as INamedTypeSymbol;

        if (responseType is null)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(new("MG003", "No IRequest<T>", $"'{paramsType.Name}' does not implement IRequest<T>", "Gen", DiagnosticSeverity.Warning, true), Location.None));
            return null;
        }

        var ienumerable = comp.GetTypeByMetadataName("System.Collections.Generic.IEnumerable`1");
        var checkType = responseType;
        bool isNullable = false;

        if (SymbolEqualityComparer.Default.Equals(responseType.OriginalDefinition, comp.GetTypeByMetadataName("System.Nullable`1")))
        {
            checkType = responseType.TypeArguments[0] as INamedTypeSymbol;
            isNullable = true;
        }

        var elementType = checkType?.AllInterfaces.Append(checkType)
            .FirstOrDefault(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, ienumerable))
            ?.TypeArguments[0] as INamedTypeSymbol;

        if (elementType is not null)
        {
            string retType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new(retType + "[]", retType, paramsType.Name, paramsType, true, false);
        }

        string respTypeStr = responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return new(respTypeStr, respTypeStr, paramsType.Name, paramsType, false, responseType.NullableAnnotation == NullableAnnotation.Annotated || isNullable);
    }

    private static INamedTypeSymbol? FindParamsType(Compilation comp, string methodName)
    {
        var names = new[] { 
            $"{methodName}Params", 
            $"{methodName}RequestParam",
            methodName.EndsWith("s") ? $"{methodName.Substring(0, methodName.Length - 1)}Params" : null,
            methodName.EndsWith("Full") ? $"{methodName.Substring(0, methodName.Length - 4)}Params" : null,
        }.OfType<string>();

        var nss = new[] { "OmniSharp.Extensions.LanguageServer.Protocol.Models", "Metek.LspCli" };
        return (from ns in nss from name in names select comp.GetTypeByMetadataName($"{ns}.{name}"))
            .FirstOrDefault(t => t is not null);
    }

    private static string DeriveFieldName(string methodName, bool isCollection)
    {
        if (methodName is "QueryAnnotationTree" or "QueryAnnotationRange") return "AnnotationTrees";
        if (methodName == "QueryObjectTree") return "ObjectTrees";
        if (methodName is "SemanticTokensFull" or "SemanticTokensRange") return "SemanticTokens";

        if (methodName.EndsWith("Prepare")) return methodName.Substring(0, methodName.Length - 7) + "Items";
        return !isCollection ? methodName : (methodName.EndsWith("s") ? methodName : methodName + "s");
    }

    private void TrackField(List<(string name, string type, string? none)> fields, MethodResult mr, string resultField)
    {
        fields.RemoveAll(f => f.name == resultField);
        fields.Add(mr.IsCollection 
            ? (resultField, $"SortedDictionary<string, {mr.ElementType}[]>", "None" + resultField)
            : (resultField, $"SortedDictionary<string, {mr.ReturnType}>", null));
    }

    private static void GenerateDriverResults(StringBuilder sb, List<(string name, string type, string? none)> fields)
    {
        if (fields.Count == 0) return;
        sb.AppendLine("public partial struct DriverResults\n{");
        foreach (var (name, type, _) in fields) sb.AppendLine($"    public readonly {type} {name} = [];");
        sb.AppendLine();
        foreach (var (_, type, none) in fields)
        {
            if (none is null) continue;
            string elemType = type.Replace("SortedDictionary<string, ", "").TrimEnd('>');
            sb.AppendLine($"    internal readonly {elemType} {none} = [];");
        }
        sb.AppendLine("}");
    }

    private static string GetResultsKey(List<string> paramNames)
    {
        if (paramNames.Contains("startLine")) return "$\"{fileName}:{startLine}:{startCharacter}:{endLine}:{endCharacter}\"";
        if (paramNames.Contains("line")) return "$\"{fileName}:{line}:{character}\"";
        return paramNames.Contains("query") ? "query" : (paramNames.Contains("_path") || paramNames.Contains("path") ? paramNames[0] : "fileName");
    }

    private static string ParamToDecl(string name) => name switch
    {
        "fileName" or "path" or "_path" or "query" => "string " + name,
        "line" or "character" or "startLine" or "startCharacter" or "endLine" or "endCharacter" => "int " + name,
        "_recursive" or "recursive" => "bool " + name,
        "range" => "OmniSharp.Extensions.LanguageServer.Protocol.Models.Range range",
        _ => "string " + name,
    };

    private static List<string> DefaultParams(string table) => table switch
    {
        "DOC" => ["fileName"],
        "TDP" => ["fileName", "line", "character"],
        "WSP" => ["query"],
        _ => ["fileName"],
    };
}

internal static class KeyValuePairExtensions
{
    public static void Deconstruct<TKey, TValue>(this KeyValuePair<TKey, TValue> kvp, out TKey key, out TValue value)
    {
        key = kvp.Key;
        value = kvp.Value;
    }
}
}