using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Metek.LspCli.Generators;

[Generator]
public sealed class NotificationRegistrationGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
// <auto-generated/>
namespace Metek.LspCli
{
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class RegisterNotificationAttribute : System.Attribute
    {
        public string Method { get; }
        public RegisterNotificationAttribute(string method) => Method = method;
    }
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("RegisterNotificationAttribute.g.cs", AttributeSource));

        var methods = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
            transform: static (ctx, _) =>
            {
                var cds = (ClassDeclarationSyntax)ctx.Node;
                var methods = new List<string>();
                foreach (var attrList in cds.AttributeLists)
                foreach (var attr in attrList.Attributes)
                {
                    var name = attr.Name.ToString();
                    if (name is not ("RegisterNotification" or "RegisterNotificationAttribute"))
                        continue;
                    if (attr.ArgumentList?.Arguments.Count < 1) continue;
                    var arg = attr.ArgumentList.Arguments[0].Expression;
                    if (arg is LiteralExpressionSyntax lit && lit.IsKind(SyntaxKind.StringLiteralExpression))
                        methods.Add(lit.Token.ValueText);
                }
                return methods.Count > 0 ? methods : null;
            })
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(methods, Generate);
    }

    private static void Generate(SourceProductionContext ctx, ImmutableArray<List<string>> methods)
    {
        var all = methods.SelectMany(m => m!).Distinct().Order().ToList();
        if (all.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("""
// <auto-generated/>
namespace Metek.LspCli
{
    public partial class Driver
    {
        public void ConfigureNotifications(OmniSharp.Extensions.LanguageServer.Client.LanguageClientOptions options)
        {
""");
        foreach (var m in all)
            sb.AppendLine($"            options.OnJsonNotification(\"{m}\", t => StoreNotification(\"{m}\", t));");
        sb.AppendLine("""
        }
    }
}
""");
        ctx.AddSource("Driver.ConfigureNotifications.g.cs", sb.ToString());
    }
}
